/* curl AukOS config -- generated by pmpt, adjust for actual curl configure */
#ifndef AUKOS_CURL_CONFIG_H
#define AUKOS_CURL_CONFIG_H

#define HAVE_CONFIG_H 1
#define __AUKOS__ 1

/* Operating system */
#define OS "x86_64-unknown-none-aukos"
#define CURL_OS "AukOS"

/* Headers */
#define HAVE_STDARG_H 1
#define HAVE_STDDEF_H 1
#define HAVE_STDINT_H 1
#define HAVE_STDLIB_H 1
#define HAVE_STRING_H 1
#define HAVE_STRINGS_H 1
#define HAVE_UNISTD_H 1
#define HAVE_FCNTL_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1
#define HAVE_SYS_SOCKET_H 1
#define HAVE_NETDB_H 1
#define HAVE_NETINET_IN_H 1
#define HAVE_ARPA_INET_H 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_SIGNAL_H 1
#define HAVE_SYS_TIME_H 1
#define HAVE_TIME_H 1
#define HAVE_SETJMP_H 1
#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_UIO_H 1

/* Compiler features */
#define HAVE_VARIADIC_MACROS 1
#define HAVE___BUILTIN_EXPECT 1
#define HAVE___BUILTIN_UNREACHABLE 1

/* Types */
#define SIZEOF_INT 4
#define SIZEOF_LONG 8
#define SIZEOF_SIZE_T 8
#define SIZEOF_VOIDP 8
#define SIZEOF_SHORT 2
#define SIZEOF_TIME_T 8
#define SIZEOF_OFF_T 8
#define WORDS_LITTLEENDIAN 1

/* Socket API */
#define HAVE_SOCKET 1
#define HAVE_SOCKETPAIR 1
#define HAVE_CONNECT 1
#define HAVE_SENDTO 1
#define HAVE_RECVFROM 1
#define HAVE_SETSOCKOPT 1
#define HAVE_SHUTDOWN 1
#define HAVE_BIND 1
#define HAVE_LISTEN 1
#define HAVE_ACCEPT 1
#define USE_ETHERNET 1

/* Protocols (enable as available) */
#define CURL_DISABLE_TFTP 1
#define CURL_DISABLE_FTP 1
#define CURL_DISABLE_LDAP 1
#define CURL_DISABLE_TELNET 1
#define CURL_DISABLE_DICT 1
#define CURL_DISABLE_FILE 1
#define CURL_DISABLE_GOPHER 1
#define CURL_DISABLE_IMAP 1
#define CURL_DISABLE_MQTT 1
#define CURL_DISABLE_POP3 1
#define CURL_DISABLE_RTSP 1
#define CURL_DISABLE_SMB 1
#define CURL_DISABLE_SMTP 1

/* Only enable HTTP for now (TCP required — not yet in kernel) */
#undef  CURL_DISABLE_HTTP
#define CURL_DISABLE_HTTP 0

/* SSL/TLS — none yet */
#define CURL_DISABLE_PROXY 1

/* Features */
#define CURL_STATICLIB 1
#define BUILDING_LIBCURL 1
#define CURL_DISABLE_COOKIES 1
#define CURL_DISABLE_CRYPTO_AUTH 1
#define CURL_DISABLE_DOH 1
#define CURL_DISABLE_HEADERS_API 1
#define CURL_DISABLE_NETRC 1
#define CURL_DISABLE_NTLM 1
#define CURL_DISABLE_PARSEDATE 1
#define CURL_DISABLE_VERBOSE_STRINGS 1
#define CURL_DISABLE_PROGRESS_METER 1

/* Use AukOS getaddrinfo stub */
#define HAVE_GETADDRINFO 1
#define HAVE_GETNAMEINFO 1
#define ENABLE_IPV6 0

#endif
