#ifndef AUKOS_NASM_CONFIG_H
#define AUKOS_NASM_CONFIG_H

#define HAVE_INTTYPES_H 1
#define HAVE_STDARG_H 1
#define HAVE_STRINGS_H 1
#define HAVE_FCNTL_H 1
#define HAVE_UNISTD_H 1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H 1

#define HAVE_VARIADIC_MACROS 1
#define HAVE_FUNC_NAME 1
#define HAVE_STDC_INLINE 1
#define HAVE_TYPEOF 1
#define HAVE___BUILTIN_EXPECT 1
#define HAVE___BUILTIN_UNREACHABLE 1
#define HAVE___BUILTIN_CONSTANT_P 1
#define HAVE___BUILTIN_CHOOSE_EXPR 1
#define HAVE___BUILTIN_PREFETCH 1
#define HAVE___BUILTIN_CLZ 1
#define HAVE___BUILTIN_CLZLL 1

#define HAVE_STRCASECMP 1
#define HAVE_DECL_STRCASECMP 1
#define HAVE_STRNCASECMP 1
#define HAVE_DECL_STRNCASECMP 1
#define HAVE_ISCNTRL 1
#define HAVE_ISASCII 1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1

#define HAVE_FTRUNCATE 1
#define HAVE_FSEEKO 1
#define HAVE_FILENO 1
#define HAVE_ACCESS 1
#define HAVE_STRUCT_STAT 1
#define HAVE_STAT 1
#define HAVE_FSTAT 1
#define HAVE_S_ISREG 1

#define WORDS_LITTLEENDIAN 1

#include "config/unconfig.h"

#endif
